#environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: mariadb
  DB_NAME: example
  DB_USER: root 
---
#secrets
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db-password: ZXhhbXBsZQ==
---
#mariadb volume pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/mariadb
---
#mariadb volume claim pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

#mariadb Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
#mariadb service
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb
---
#php app Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-crud
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      hello-php: php-crud
  template:
    metadata:
      labels:
        hello-php: php-crud
    spec:
      containers:
      - name: php-crud
        image: omernawaz29/php-crud
        imagePullPolicy: Always
        volumeMounts:
        - name: db-password
          mountPath: /etc/secrets
          readOnly: true
          
        env:
        - name: PASSWORD_FILE_PATH
          value: /etc/secrets/db-password
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        
 
        ports:
        - containerPort: 80
      volumes:
      - name: db-password
        secret:
          secretName: db-secret
        
---
#php app service
apiVersion: v1
kind: Service
metadata:
  name: php-crud
  namespace: default
spec:
  type: NodePort
  selector:
    hello-php: php-crud
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
